TWEET_COUNT_PER_USER_EPOCH = 100

# LANGUAGE_MODEL_TYPE = "bert-base-uncased"
# LANGUAGE_MODEL_FEATURE_SIZE = 768
LANGUAGE_MODEL_TYPE = "prajjwal1/bert-tiny"
LANGUAGE_MODEL_FEATURE_SIZE = 128
LANGUAGE_MODEL_VOCAB_SIZE = 30522
LANGUAGE_MODEL_CLS_TOKEN_ID = 101
LANGUAGE_MODEL_SEP_TOKEN_ID = 102
LANGUAGE_MODEL_MASK_TOKEN_ID = 103
LANGUAGE_MODEL_PAD_TOKEN_ID = 0
LANGUAGE_MODEL_UNMASK_TOKEN_ID = 0
